### ISSUE TITLE
Show original poster's nickname on thumbnail

### ISSUE THREAD

**Issue by iiiGerardoiii** [on-three/weeabot#51]
Showing the nickname of the person who originally posted the file could be very helpful, as people tend to ask "who posted this" or "lol who did this?"

e.g.
![rrtst](https://cloud.githubusercontent.com/assets/6264194/6913066/f4caadac-d737-11e4-80e3-1e3d175b0088.png)

**Comment by ScottSteiner** [comment]
What an awful idea.

**Comment by iiiGerardoiii** [comment]
For you.

**Comment by iiiGerardoiii** [comment]
Whoops wrong repo.

**Comment by ScottSteiner** [comment]
What an awful close
